language: node_js
node_js:
  - stable
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov mocha istanbul
script:
  - npm test
after_success:
  - istanbul cover _mocha
  - codecov